version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:example@db:3306/todo_db
      - SECRET_KEY=supersecretkey
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - todo_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network:
    driver: bridge